/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oxgame;

import static oxgame.Register.sendToServer;
import javax.swing.*;
/**
 *
 * @author best_
 */
public class Ox_Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Ox_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        userPass = new javax.swing.JPasswordField();
        Confirm = new javax.swing.JLabel();
        confirmPass = new javax.swing.JPasswordField();
        sender = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        Surname = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        Header.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        Header.setForeground(new java.awt.Color(240, 240, 240));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Register");
        Header.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Header);
        Header.setBounds(407, 30, 210, 60);

        Username.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(240, 240, 240));
        Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username.setText("Username:");
        getContentPane().add(Username);
        Username.setBounds(206, 140, 100, 50);

        userField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        getContentPane().add(userField);
        userField.setBounds(320, 150, 100, 25);

        Password.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(240, 240, 240));
        Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password.setText("Password:");
        getContentPane().add(Password);
        Password.setBounds(206, 205, 100, 50);

        userPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassActionPerformed(evt);
            }
        });
        getContentPane().add(userPass);
        userPass.setBounds(320, 215, 100, 25);

        Confirm.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        Confirm.setForeground(new java.awt.Color(240, 240, 240));
        Confirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Confirm.setText("Confirm Password:");
        getContentPane().add(Confirm);
        Confirm.setBounds(126, 270, 180, 50);

        confirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPass);
        confirmPass.setBounds(320, 280, 100, 25);

        sender.setText("Send");
        sender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senderMouseClicked(evt);
            }
        });
        sender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderActionPerformed(evt);
            }
        });
        getContentPane().add(sender);
        sender.setBounds(462, 420, 100, 23);

        Name.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(240, 240, 240));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Name:");
        getContentPane().add(Name);
        Name.setBounds(562, 140, 100, 50);
        getContentPane().add(name);
        name.setBounds(664, 150, 100, 25);

        Surname.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        Surname.setForeground(new java.awt.Color(240, 240, 240));
        Surname.setText("Surname:");
        getContentPane().add(Surname);
        Surname.setBounds(562, 205, 100, 50);
        getContentPane().add(surname);
        surname.setBounds(664, 215, 100, 25);

        Email.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(240, 240, 240));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("Email:");
        getContentPane().add(Email);
        Email.setBounds(562, 270, 100, 50);
        getContentPane().add(email);
        email.setBounds(664, 280, 100, 25);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\best_\\Documents\\NetBeansProjects\\oxgame\\src\\9b75a0e49299595d79b860afdce3bf64.jpg")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1024, 768);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void senderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senderMouseClicked
      String password = new String(userPass.getPassword());
      String confirmPassword = new String(confirmPass.getPassword());
        System.out.println(password);
        
      if(password.equals(confirmPassword))
      {
          String username = userField.getText();
          String getName = name.getText();
          String getSurname = surname.getText();
          String getEmail = email.getText();
          try{
            sendToServer(username,password,getName,getSurname,getEmail);
            System.exit(0);
          }
          catch(Exception e){
             
          }
      }
      else
      {
          JOptionPane.showMessageDialog(null, "Confirm password error!!", "Error!!", JOptionPane.ERROR_MESSAGE);
          userField.setText("");
          name.setText("");
          surname.setText("");
          email.setText("");
          userPass.setText("");
          confirmPass.setText("");          
      }
    }//GEN-LAST:event_senderMouseClicked

    private void senderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senderActionPerformed

    private void userPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassActionPerformed

    private void confirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ox_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ox_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ox_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ox_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ox_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Confirm;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Surname;
    private javax.swing.JLabel Username;
    private javax.swing.JPasswordField confirmPass;
    private javax.swing.JTextField email;
    private javax.swing.JTextField name;
    private javax.swing.JButton sender;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField userField;
    private javax.swing.JPasswordField userPass;
    // End of variables declaration//GEN-END:variables
}
