/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oxgame;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author TheNineInwKung
 */
public class regisFrame extends javax.swing.JFrame {

    /**
     * Creates new form regisFrame
     */
    private int xMouse;
    private int yMouse;
    private char passwordChar;
    public void reset(){
        passwordChar = passwdCon.getEchoChar();
        username.setText("Enter Username");
        email1.setText("Enter E-Mail");
        name.setText("Enter Name");
        surname.setText("Enter Surname");
        passwd.setEchoChar ((char) 0); 
        passwd.setText("Enter Password"); 
        passwdCon.setEchoChar ((char) 0);
        passwdCon.setText("Enter Confirm Password"); 
    }
    public regisFrame() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        reset();
        username.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(username.getText().equals("Enter Username")){
                    username.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(username.getText().equals("")){
                    username.setText("Enter Username");
                }
            }
        });
        email1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(email1.getText().equals("Enter E-Mail")){
                    email1.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(email1.getText().equals("")){
                    email1.setText("Enter E-Mail");
                }
            }
        });
        name.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(name.getText().equals("Enter Name")){
                    name.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(name.getText().equals("")){
                    name.setText("Enter Name");
                }
            }
        });
        surname.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(surname.getText().equals("Enter Surname")){
                    surname.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(surname.getText().equals("")){
                    surname.setText("Enter Surname");
                }
            }
            
        });
        
        passwd.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(passwd.getText().equals("Enter Password")){
                    passwd.setText("");
                    passwd.setEchoChar(passwordChar);
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(passwd.getText().equals("")){
                    passwd.setText("Enter Password");
                    passwd.setEchoChar ((char) 0); 
                }
            }
        });
        passwdCon.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(passwdCon.getText().equals("Enter Confirm Password")){
                    passwdCon.setText("");
                    
                    passwdCon.setEchoChar(passwordChar);
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(passwdCon.getText().equals("")){
                    passwdCon.setText("Enter Confirm Password");
                    passwdCon.setEchoChar ((char) 0); 
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_close = new javax.swing.JLabel();
        input = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        passwdCon = new javax.swing.JPasswordField();
        passwd = new javax.swing.JPasswordField();
        img_icon = new javax.swing.JLabel();
        bt_regis = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        bgShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        bt_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oxgame/bt_close.png"))); // NOI18N
        bt_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_closeMouseClicked(evt);
            }
        });
        getContentPane().add(bt_close);
        bt_close.setBounds(705, 75, 39, 39);

        input.setOpaque(false);
        input.setLayout(null);

        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setText("Name");
        name.setToolTipText("");
        input.add(name);
        name.setBounds(150, 250, 510, 50);

        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("Username");
        username.setToolTipText("");
        input.add(username);
        username.setBounds(150, 130, 510, 50);

        email1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email1.setText("E-mail");
        email1.setToolTipText("");
        input.add(email1);
        email1.setBounds(150, 190, 510, 50);

        surname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        surname.setText("Surname");
        surname.setToolTipText("");
        input.add(surname);
        surname.setBounds(150, 310, 510, 50);

        passwdCon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.add(passwdCon);
        passwdCon.setBounds(150, 430, 510, 50);

        passwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.add(passwd);
        passwd.setBounds(150, 370, 510, 50);

        img_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oxgame/icon.png"))); // NOI18N
        input.add(img_icon);
        img_icon.setBounds(340, 0, 126, 126);

        bt_regis.setBackground(new java.awt.Color(49, 141, 166));
        bt_regis.setForeground(new java.awt.Color(255, 255, 255));
        bt_regis.setText("REGISTER");
        bt_regis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bt_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_regisActionPerformed(evt);
            }
        });
        input.add(bt_regis);
        bt_regis.setBounds(150, 500, 510, 50);

        getContentPane().add(input);
        input.setBounds(0, 0, 800, 600);

        bg.setOpaque(false);
        bg.setLayout(new javax.swing.BoxLayout(bg, javax.swing.BoxLayout.LINE_AXIS));

        bgShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oxgame/bg.png"))); // NOI18N
        bgShow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgShowMouseDragged(evt);
            }
        });
        bgShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgShowMousePressed(evt);
            }
        });
        bg.add(bgShow);

        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeMouseClicked
        dispose();
    }//GEN-LAST:event_bt_closeMouseClicked

    private void bt_regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_regisActionPerformed
        if(username.getText().equals("Enter Username") || email1.getText().equals("Enter E-Mail") || name.getText().equals("Enter Name") || surname.getText().equals("Enter Surname") || passwd.getText().equals("Enter Password") || passwdCon.getText().equals("Enter Confirm Password")){
            JOptionPane.showMessageDialog(null,
	    "Please Enter Username, E-Mail, Name, Surname, Password, Confirm Password.",
	    "Register",
	    JOptionPane.PLAIN_MESSAGE);
        }
        else if(!String.copyValueOf(passwd.getPassword()).equals(String.copyValueOf(passwdCon.getPassword()))){
            JOptionPane.showMessageDialog(null,
	    "Password and Confirm Password not same.",
	    "Register",
	    JOptionPane.PLAIN_MESSAGE);
        }else{
            try{
                JSONObject obj = Register.sendToServer(username.getText(), passwd.getPassword().toString(), name.getText(), surname.getText(), email1.getText()); 
                if(obj.getInt("status")==0){
                    JOptionPane.showMessageDialog(null,obj.getString("message"),"Register",JOptionPane.PLAIN_MESSAGE);
                    reset();
                }else{
                    JOptionPane.showMessageDialog(null,obj.getString("message"),"error",JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
            }
           
        }
        
    }//GEN-LAST:event_bt_regisActionPerformed

    private void bgShowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgShowMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_bgShowMouseDragged

    private void bgShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgShowMousePressed
       xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgShowMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regisFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgShow;
    private javax.swing.JLabel bt_close;
    private javax.swing.JButton bt_regis;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel img_icon;
    private javax.swing.JPanel input;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JPasswordField passwdCon;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
