/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RHiaHoa
 */
public class Regiter extends javax.swing.JFrame {

    private String username;
    private String password;
    private String confirm;
    private String email;
    private String name;
    private String surname;

    public Regiter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_login = new javax.swing.JButton();
        bt_singup = new javax.swing.JButton();
        field_Username = new javax.swing.JTextField();
        field_password = new javax.swing.JTextField();
        field_confirmpassword = new javax.swing.JTextField();
        field_email = new javax.swing.JTextField();
        logo_register = new javax.swing.JLabel();
        text_username = new javax.swing.JLabel();
        text_password = new javax.swing.JLabel();
        text_confirmpassword = new javax.swing.JLabel();
        text_email = new javax.swing.JLabel();
        field_name = new javax.swing.JTextField();
        field_surname = new javax.swing.JTextField();
        text_name = new javax.swing.JLabel();
        text_surname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 650));
        setMinimumSize(new java.awt.Dimension(500, 650));
        setPreferredSize(new java.awt.Dimension(500, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        bt_login.setText("LOGIN");
        getContentPane().add(bt_login);
        bt_login.setBounds(120, 550, 270, 40);

        bt_singup.setText("SING UP");
        bt_singup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_singupActionPerformed(evt);
            }
        });
        getContentPane().add(bt_singup);
        bt_singup.setBounds(120, 490, 270, 40);

        field_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(field_Username);
        field_Username.setBounds(120, 260, 270, 30);
        getContentPane().add(field_password);
        field_password.setBounds(120, 320, 270, 30);
        getContentPane().add(field_confirmpassword);
        field_confirmpassword.setBounds(120, 380, 270, 30);
        getContentPane().add(field_email);
        field_email.setBounds(120, 440, 270, 30);

        logo_register.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        logo_register.setText("REGISTER");
        getContentPane().add(logo_register);
        logo_register.setBounds(140, 20, 240, 100);

        text_username.setText("Username");
        getContentPane().add(text_username);
        text_username.setBounds(120, 240, 130, 14);

        text_password.setText("Password");
        getContentPane().add(text_password);
        text_password.setBounds(120, 300, 60, 14);

        text_confirmpassword.setText("Confirm Password");
        getContentPane().add(text_confirmpassword);
        text_confirmpassword.setBounds(120, 360, 110, 14);

        text_email.setText("E-mail");
        getContentPane().add(text_email);
        text_email.setBounds(120, 420, 50, 14);
        getContentPane().add(field_name);
        field_name.setBounds(120, 140, 270, 30);
        getContentPane().add(field_surname);
        field_surname.setBounds(120, 200, 270, 30);

        text_name.setText("Name");
        getContentPane().add(text_name);
        text_name.setBounds(120, 120, 110, 14);

        text_surname.setText("Surname");
        getContentPane().add(text_surname);
        text_surname.setBounds(120, 180, 150, 14);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_singupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_singupActionPerformed
        this.username = field_Username.getText();
        this.password = field_password.getText();
        this.confirm = field_confirmpassword.getText();
        this.email = field_email.getText();
        this.name = field_name.getText();
        this.surname = field_surname.getText();

        try {
            Regis.sendToServer(username, password, name, surname, email);
        } catch (Exception ex) {
            System.out.println("ERROR");
        }
    }//GEN-LAST:event_bt_singupActionPerformed

    private void field_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_UsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regiter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_singup;
    private javax.swing.JTextField field_Username;
    private javax.swing.JTextField field_confirmpassword;
    private javax.swing.JTextField field_email;
    private javax.swing.JTextField field_name;
    private javax.swing.JTextField field_password;
    private javax.swing.JTextField field_surname;
    private javax.swing.JLabel logo_register;
    private javax.swing.JLabel text_confirmpassword;
    private javax.swing.JLabel text_email;
    private javax.swing.JLabel text_name;
    private javax.swing.JLabel text_password;
    private javax.swing.JLabel text_surname;
    private javax.swing.JLabel text_username;
    // End of variables declaration//GEN-END:variables
}
